source 'https://rubygems.org'

gem 'rspec'
gem 'rspec-benchmark', git: 'https://github.com/piotrmurach/rspec-benchmark'
gem 'benchmark-perf'
gem 'benchmark-ips'
gem 'pry'
gem 'stackprof'
gem 'ruby-prof'
gem 'memory_profiler'
